# Generated by Django 2.0.2 on 2018-03-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20180224_1743'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messages',
            table='messages',
        ),
    ]
